insert into companies (name) values ('Quadro Holdings LTEE') on conflict (name) do nothing;

insert into platforms (key, name, required_for_service_check) values
  ('clover','Clover',false),
  ('doordash','DoorDash',true),
  ('uber_eats','Uber Eats',true),
  ('skip_the_dishes','SkipTheDishes',true),
  ('too_good_to_go','Too Good To Go',false)
on conflict (key) do update set name = excluded.name, required_for_service_check = excluded.required_for_service_check;

insert into locations (company_id, code, name, address_line_1, city, province, postal_code, country) values
((select id from companies where name='Quadro Holdings LTEE'), 'NDG_MAIN', 'NDG MAIN', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA'),
((select id from companies where name='Quadro Holdings LTEE'), 'NDG_6284', 'NDG 6284', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA'),
((select id from companies where name='Quadro Holdings LTEE'), 'HOCHELAGA', 'HOCHELAGA', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA'),
((select id from companies where name='Quadro Holdings LTEE'), 'SAINT_LEONARD', 'SAINT-LÉONARD', '5837 Rue Jean-Talon E', 'Saint-Léonard', 'QC', 'H1S 1M4', 'CA')
on conflict (code) do update set name=excluded.name, address_line_1=excluded.address_line_1, city=excluded.city, province=excluded.province, postal_code=excluded.postal_code;

insert into brands (company_id, name) values
((select id from companies where name='Quadro Holdings LTEE'), 'Nutrition Shake'),
((select id from companies where name='Quadro Holdings LTEE'), 'OOeuf'),
((select id from companies where name='Quadro Holdings LTEE'), 'Po Poulet'),
((select id from companies where name='Quadro Holdings LTEE'), 'Pi Pita'),
((select id from companies where name='Quadro Holdings LTEE'), 'OCRÊPE'),
((select id from companies where name='Quadro Holdings LTEE'), 'PPP Pizzeria'),
((select id from companies where name='Quadro Holdings LTEE'), 'Bin molle & Bin Dure'),
((select id from companies where name='Quadro Holdings LTEE'), 'Gateau Montreal'),
((select id from companies where name='Quadro Holdings LTEE'), 'Pizza Inntime'),
((select id from companies where name='Quadro Holdings LTEE'), 'Dejeuner & Dinner'),
((select id from companies where name='Quadro Holdings LTEE'), 'Pita Libanais'),
((select id from companies where name='Quadro Holdings LTEE'), 'Poulet Poulet'),
((select id from companies where name='Quadro Holdings LTEE'), 'Taco Mexican'),
((select id from companies where name='Quadro Holdings LTEE'), 'Cafe Bolon'),
((select id from companies where name='Quadro Holdings LTEE'), 'Mythos 2 Go'),
((select id from companies where name='Quadro Holdings LTEE'), 'Place Afrique'),
((select id from companies where name='Quadro Holdings LTEE'), 'Crèmerie Bin Molle Bin Dure'),
((select id from companies where name='Quadro Holdings LTEE'), 'Too Good To Go')
on conflict (name) do nothing;

insert into platform_stores (platform_id, brand_id, location_id, external_business_id, external_store_id, store_name, address_line_1, city, province, postal_code, country, activation_status, open_status, status_symbol, needs_review, review_note, raw_payload) values
((select id from platforms where key='doordash'), (select id from brands where name='Nutrition Shake'), (select id from locations where code='NDG_6284'), '12606537', '', 'Nutrition', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "Nutrition Shake", "store_name": "Nutrition", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12606537"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Nutrition Shake'), (select id from locations where code='SAINT_LEONARD'), '12606537', '', 'Nutrition Shake Saint Leonard', '5837 Rue Jean-Talon E', 'Saint-Léonard', 'QC', 'H1S 1M4', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Nutrition Shake", "store_name": "Nutrition Shake Saint Leonard", "location_code": "SAINT_LEONARD", "address_line_1": "5837 Rue Jean-Talon E", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12606537"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Nutrition Shake'), (select id from locations where code='NDG_MAIN'), '12606537', '', 'Nutrition Shake (NOTRE-DAME-DE-GRÂCE)', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Nutrition Shake", "store_name": "Nutrition Shake (NOTRE-DAME-DE-GRÂCE)", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12606537"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Nutrition Shake'), (select id from locations where code='HOCHELAGA'), '12606537', '', 'Nutrition Shake (HOCHELAGA)', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "Nutrition Shake", "store_name": "Nutrition Shake (HOCHELAGA)", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12606537"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='OOeuf'), (select id from locations where code='NDG_6284'), '12748843', '', 'OOEUF Express NDG', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "OOeuf", "store_name": "OOEUF Express NDG", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12748843"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='OOeuf'), (select id from locations where code='NDG_6284'), '12748843', '', 'OOEUF SUPREME', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "OOeuf", "store_name": "OOEUF SUPREME", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12748843"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='OOeuf'), (select id from locations where code='HOCHELAGA'), '12748843', '', 'OOEUF (HOCHELAGA)', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "OOeuf", "store_name": "OOEUF (HOCHELAGA)", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12748843"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='OOeuf'), (select id from locations where code='NDG_MAIN'), '12748843', '', 'OOEUF (NOTRE-DAME-DE-GRÂCE)', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "OOeuf", "store_name": "OOEUF (NOTRE-DAME-DE-GRÂCE)", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12748843"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Po Poulet'), (select id from locations where code='NDG_6284'), '12796649', '', 'Po Poulet NDG', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "Po Poulet", "store_name": "Po Poulet NDG", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12796649"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Po Poulet'), (select id from locations where code='HOCHELAGA'), '12796649', '', 'Poulet Poulet (HOCHELAGA)', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "Po Poulet", "store_name": "Poulet Poulet (HOCHELAGA)", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12796649"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Po Poulet'), (select id from locations where code='SAINT_LEONARD'), '12796649', '', 'Po Poulet (ST LEONARD)', '5837 Rue Jean-Talon E', 'Saint-Léonard', 'QC', 'H1S 1M4', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Po Poulet", "store_name": "Po Poulet (ST LEONARD)", "location_code": "SAINT_LEONARD", "address_line_1": "5837 Rue Jean-Talon E", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12796649"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Po Poulet'), (select id from locations where code='NDG_MAIN'), '12796649', '', 'Po Poulet Hochelaga', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', true, 'Name says Hochelaga but address is NDG MAIN.', '{"brand_name": "Po Poulet", "store_name": "Po Poulet Hochelaga", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12796649", "needs_review": true, "review_note": "Name says Hochelaga but address is NDG MAIN."}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Pi Pita'), (select id from locations where code='NDG_6284'), '12798384', '', 'Pi Pita', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Pi Pita", "store_name": "Pi Pita", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12798384"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Pi Pita'), (select id from locations where code='HOCHELAGA'), '12798384', '', 'Pi Pita (HOCHELAGA)', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "Pi Pita", "store_name": "Pi Pita (HOCHELAGA)", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12798384"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Pi Pita'), (select id from locations where code='NDG_MAIN'), '12798384', '', 'Pi Pita (Montréal NOTRE-DAME-DE-GRÂCE)', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Pi Pita", "store_name": "Pi Pita (Montréal NOTRE-DAME-DE-GRÂCE)", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12798384"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='OCRÊPE'), (select id from locations where code='NDG_6284'), '12798510', '', 'OCRÊPE', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "OCRÊPE", "store_name": "OCRÊPE", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12798510"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='OCRÊPE'), (select id from locations where code='HOCHELAGA'), '12798510', '', 'OCRÊPE (HOCHELAGA)', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "OCRÊPE", "store_name": "OCRÊPE (HOCHELAGA)", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12798510"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='OCRÊPE'), (select id from locations where code='NDG_MAIN'), '12798510', '', 'OCRÊPE (NOTRE-DAME-DE-GRÂCE)', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "OCRÊPE", "store_name": "OCRÊPE (NOTRE-DAME-DE-GRÂCE)", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12798510"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='PPP Pizzeria'), (select id from locations where code='HOCHELAGA'), '12820103', '', 'PPP Pizzeria (HOCHELAGA)', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "PPP Pizzeria", "store_name": "PPP Pizzeria (HOCHELAGA)", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12820103"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='PPP Pizzeria'), (select id from locations where code='NDG_6284'), '12820103', '', 'PPP Pizzeria', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "PPP Pizzeria", "store_name": "PPP Pizzeria", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12820103"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='PPP Pizzeria'), (select id from locations where code='NDG_MAIN'), '12820103', '', 'PPP Pizzeria (NOTRE-DAME-DE-GRÂCE)', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "PPP Pizzeria", "store_name": "PPP Pizzeria (NOTRE-DAME-DE-GRÂCE)", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12820103"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Bin molle & Bin Dure'), (select id from locations where code='HOCHELAGA'), '12844632', '', 'Bin Molle & Bin Dure (HOCHELAGA)', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Bin molle & Bin Dure", "store_name": "Bin Molle & Bin Dure (HOCHELAGA)", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12844632"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Bin molle & Bin Dure'), (select id from locations where code='NDG_6284'), '12844632', '', 'Bin molle & Bin Dure NDG', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Bin molle & Bin Dure", "store_name": "Bin molle & Bin Dure NDG", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12844632"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Gateau Montreal'), (select id from locations where code='NDG_MAIN'), '12847317', '', 'Gateau Montréal (NOTRE-DAME-DE-GRÂCE)', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Gateau Montreal", "store_name": "Gateau Montréal (NOTRE-DAME-DE-GRÂCE)", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12847317"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Gateau Montreal'), (select id from locations where code='HOCHELAGA'), '12847317', '', 'Gâteau Montréal (HOCHELAGA)', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "Gateau Montreal", "store_name": "Gâteau Montréal (HOCHELAGA)", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12847317"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Gateau Montreal'), (select id from locations where code='NDG_6284'), '12847317', '', 'Gateau Montreal', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "Gateau Montreal", "store_name": "Gateau Montreal", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12847317"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Pizza Inntime'), (select id from locations where code='NDG_MAIN'), '12885507', '', 'Pizza INNTIME Montréal', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Pizza Inntime", "store_name": "Pizza INNTIME Montréal", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12885507"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Pizza Inntime'), (select id from locations where code='NDG_6284'), '12885507', '', 'Pizza INNTIME', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "Pizza Inntime", "store_name": "Pizza INNTIME", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "12885507"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Pizza Inntime'), (select id from locations where code='HOCHELAGA'), '12885507', '', 'PIZZA INNTIME (HOCHELAGA)', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Pizza Inntime", "store_name": "PIZZA INNTIME (HOCHELAGA)", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "12885507"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Place Afrique'), (select id from locations where code='NDG_6284'), '13838349', '', 'PLACE AFRIQUE NDG', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Place Afrique", "store_name": "PLACE AFRIQUE NDG", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "13838349"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Place Afrique'), (select id from locations where code='HOCHELAGA'), '13838349', '', 'Place D''Afrique HOCHELAGA', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Place Afrique", "store_name": "Place D''Afrique HOCHELAGA", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "13838349"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Place Afrique'), (select id from locations where code='NDG_MAIN'), '13838349', '', 'PlaceAfrique(NOTRE-DAME-DE-GRÂCE)', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Place Afrique", "store_name": "PlaceAfrique(NOTRE-DAME-DE-GRÂCE)", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "13838349"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Mythos 2 Go'), (select id from locations where code='NDG_6284'), '13837955', '', 'Mythos 2 Go NDG', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Mythos 2 Go", "store_name": "Mythos 2 Go NDG", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "13837955"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Mythos 2 Go'), (select id from locations where code='HOCHELAGA'), '13837955', '', 'Mythos 2 Go HOCHELAGA', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Mythos 2 Go", "store_name": "Mythos 2 Go HOCHELAGA", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "13837955"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Mythos 2 Go'), (select id from locations where code='NDG_MAIN'), '13837955', '', 'Mythos 2 Go(NOTRE-DAME-DE-GRÂCE)', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Mythos 2 Go", "store_name": "Mythos 2 Go(NOTRE-DAME-DE-GRÂCE)", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "13837955"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Cafe Bolon'), (select id from locations where code='NDG_6284'), '13080151', '', 'Cafe Bolon NDG', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Cafe Bolon", "store_name": "Cafe Bolon NDG", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "13080151"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Cafe Bolon'), (select id from locations where code='NDG_MAIN'), '13080151', '', 'Cafe Bolon(NOTRE-DAME-DE-GRÂCE)', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Cafe Bolon", "store_name": "Cafe Bolon(NOTRE-DAME-DE-GRÂCE)", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "13080151"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Cafe Bolon'), (select id from locations where code='HOCHELAGA'), '13080151', '', 'Cafe Bolon (HOCHELAGA)', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Cafe Bolon", "store_name": "Cafe Bolon (HOCHELAGA)", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "13080151"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Taco Mexican'), (select id from locations where code='NDG_MAIN'), '13080099', '', 'Taco Mexican (NOTRE-DAME-DE-GRÂCE)', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Taco Mexican", "store_name": "Taco Mexican (NOTRE-DAME-DE-GRÂCE)", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "13080099"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Taco Mexican'), (select id from locations where code='HOCHELAGA'), '13080099', '', 'Taco Mexican HOCHELAGA', '3583 Rue Sainte-Catherine E', 'Montréal', 'QC', 'H1W 2E6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "Taco Mexican", "store_name": "Taco Mexican HOCHELAGA", "location_code": "HOCHELAGA", "address_line_1": "3583 Rue Sainte-Catherine E", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "13080099"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Taco Mexican'), (select id from locations where code='NDG_6284'), '13080099', '', 'Taco Mexican NDG', '6284 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'active', 'closed', 'Z', false, '', '{"brand_name": "Taco Mexican", "store_name": "Taco Mexican NDG", "location_code": "NDG_6284", "address_line_1": "6284 Av Somerled", "activation_status": "active", "open_status": "closed", "status_symbol": "Z", "external_business_id": "13080099"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Crèmerie Bin Molle Bin Dure'), (select id from locations where code='SAINT_LEONARD'), '14353843', '', 'Crèmerie Bin Molle Bin Dure ST LÉONARD', '5837 Rue Jean-Talon E', 'Saint-Léonard', 'QC', 'H1S 1M4', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Crèmerie Bin Molle Bin Dure", "store_name": "Crèmerie Bin Molle Bin Dure ST LÉONARD", "location_code": "SAINT_LEONARD", "address_line_1": "5837 Rue Jean-Talon E", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "14353843"}'::jsonb),
((select id from platforms where key='doordash'), (select id from brands where name='Crèmerie Bin Molle Bin Dure'), (select id from locations where code='NDG_MAIN'), '14353843', '', 'Crèmerie Bin Molle Bin Dure (NOTRE-DAME-DE-GRÂCE)', '6280 Av Somerled', 'Montréal', 'QC', 'H3X 2B6', 'CA', 'deactivated', 'unknown', 'grey_circle', false, '', '{"brand_name": "Crèmerie Bin Molle Bin Dure", "store_name": "Crèmerie Bin Molle Bin Dure (NOTRE-DAME-DE-GRÂCE)", "location_code": "NDG_MAIN", "address_line_1": "6280 Av Somerled", "activation_status": "deactivated", "open_status": "unknown", "status_symbol": "grey_circle", "external_business_id": "14353843"}'::jsonb)
on conflict (platform_id, brand_id, location_id, store_name) do nothing;


-- Connector config placeholders. Secrets are not stored here; secret_reference points to env/vault names only.
insert into platform_connector_configs (platform_id, mode, enabled, credential_status, secret_reference, notes)
select id,
  case key when 'clover' then 'oauth' when 'doordash' then 'api_key' when 'uber_eats' then 'oauth' when 'skip_the_dishes' then 'api_key' when 'too_good_to_go' then 'api_key' else 'disabled' end,
  false,
  'missing',
  upper(key) || '_SERVER_SECRET',
  'Live connector disabled until credentials, health check, and owner approval are complete.'
from platforms
on conflict (platform_id) do nothing;

-- Generate initial fix tasks for deactivated DoorDash stores.
insert into fix_tasks (source_type, source_id, priority, title, detail)
select 'platform_store', ps.id, 'high', 'Reactivate or verify deactivated DoorDash store', b.name || ' / ' || ps.store_name || ' / ' || l.code
from platform_stores ps
join brands b on b.id = ps.brand_id
join locations l on l.id = ps.location_id
join platforms p on p.id = ps.platform_id
where p.key='doordash' and ps.activation_status='deactivated'
  and not exists (select 1 from fix_tasks f where f.source_type = 'platform_store' and f.source_id = ps.id);
