// Default parameters and the export checklist for the finance report (sources checked 2026-10-07). Public, generic
// values only — anything specific to the owner (bank last 4, held amounts, cases) lives in private/finance/known.json;
// private/finance/rules.json can override any value below by id.
import type { ExportItem, RuleRow } from './workbook';

export const DEFAULT_RULES: RuleRow[] = [
  { id: 'gst_rate', section: 'Tax', label: 'GST (TPS) rate — taxable food and platform fees', value: 5, unit: '%', source: 'Excise Tax Act s.165(1); canada.ca GST/HST rates', confidence: 'VERIFIED' },
  { id: 'qst_rate', section: 'Tax', label: 'QST (TVQ) rate', value: 9.975, unit: '%', source: 'revenuquebec.ca — QST rate', confidence: 'VERIFIED' },
  { id: 'clover_stray_rate', section: 'Tax', label: 'Clover default tax "Sales Tax" charged on top of TPS + TVQ (should not exist)', value: 0.14975, unit: '%', source: 'Clover dashboard → Taxes (2026-10-07); Clover backup 2026-10-04: on 214 of 216 items', confidence: 'VERIFIED' },
  { id: 'dispute_uber_eats', section: 'Disputes', label: 'Uber Eats: days to dispute an adjustment / error charge (contract 14 days from notice; help centre says 30 days from the order — 14 used as the safe limit)', value: 14, unit: 'days', source: 'Uber Eats Merchant Supplemental Terms, Canada (uber.com/legal, modified 2025-09-15); merchants.ubereats.com/ca/en/order-errors', confidence: 'VERIFIED (sources differ)' },
  { id: 'dispute_doordash', section: 'Disputes', label: 'DoorDash: days to dispute an error charge (Financials → Transactions → Error charge → Dispute Charge); after that only via Support', value: 14, unit: 'days', source: 'help.doordash.com/en-ca — What are order error adjustments; Merchant ToS Canada §3/§15.1.3', confidence: 'VERIFIED' },
  { id: 'dispute_skip', section: 'Disputes', label: 'SkipTheDishes: days to dispute an adjustment (not published — check the partner agreement)', value: 7, unit: 'days', source: 'No public source; conservative assumption', confidence: 'UNCERTAIN' },
  { id: 'dispute_clover', section: 'Disputes', label: 'Clover / Fiserv: days to answer a card chargeback (Visa/Mastercard 15, Amex 14 → 14 used)', value: 14, unit: 'days', source: 'Fiserv Canada — Handling retrievals & chargebacks (June 2026); clover.com/en-CA/help — respond to a dispute', confidence: 'VERIFIED' },
  { id: 'unpaid_after_days', section: 'Holds', label: 'A statement line with no payout after this many days counts as held / not paid (weekly cycles: Uber Mon→Mon, deposits from Monday; DoorDash Mon–Sun, sent Thursday)', value: 14, unit: 'days', source: 'help.uber.com — how do store payments work; merchants.doordash.com/en-ca — financials', confidence: 'ASSUMPTION' },
  { id: 'bank_window_before', section: 'Bank matching', label: 'A deposit may appear this many days BEFORE the statement payout date', value: 3, unit: 'days', source: 'Assumption', confidence: 'ASSUMPTION' },
  { id: 'bank_window_after', section: 'Bank matching', label: 'A deposit may appear this many days AFTER the statement payout date (bank transfer 1–3 business days, weekends)', value: 10, unit: 'days', source: 'Uber 1–2 days; Clover 1–3 business days; DoorDash next day', confidence: 'ASSUMPTION' },
  { id: 'match_tolerance', section: 'Bank matching', label: 'Amount tolerance when matching a payout to a deposit', value: 0.01, unit: '$', source: 'Assumption', confidence: 'ASSUMPTION' },
  { id: 'info_uber_ads_dispute', section: 'Disputes (info)', label: 'Uber Eats ads: dispute ad charges in writing within 60 days', value: 60, unit: 'days', source: 'Uber Eats Restaurant Advertising Terms, Canada', confidence: 'VERIFIED' },
  { id: 'info_clover_fee_errors', section: 'Disputes (info)', label: 'Fiserv/Clover: report fee or statement errors in writing within 45 days, or they are deemed accepted', value: 45, unit: 'days', source: 'Fiserv Canada Merchant Terms §19.2', confidence: 'VERIFIED' },
  { id: 'plan_uber_lite', section: 'Published plans (info)', label: 'Uber Eats Lite — delivery commission (was 15 % until March 2026)', value: 20, unit: '%', source: 'merchants.ubereats.com/ca/en/pricing', confidence: 'VERIFIED' },
  { id: 'plan_uber_plus', section: 'Published plans (info)', label: 'Uber Eats Plus — delivery commission (+5 % on Uber One members\' orders = 30 %)', value: 25, unit: '%', source: 'merchants.ubereats.com/ca/en/pricing', confidence: 'VERIFIED' },
  { id: 'plan_uber_premium', section: 'Published plans (info)', label: 'Uber Eats Premium — delivery commission', value: 30, unit: '%', source: 'merchants.ubereats.com/ca/en/pricing', confidence: 'VERIFIED' },
  { id: 'plan_uber_pickup', section: 'Published plans (info)', label: 'Uber Eats pickup commission (15 % unless app prices = in-store prices)', value: 10, unit: '%', source: 'merchants.ubereats.com/ca/en/pricing', confidence: 'VERIFIED' },
  { id: 'plan_dd_basic', section: 'Published plans (info)', label: 'DoorDash Basic — delivery commission (pickup 10 %)', value: 20, unit: '%', source: 'merchants.doordash.com/en-ca/pricing', confidence: 'VERIFIED' },
  { id: 'plan_dd_plus', section: 'Published plans (info)', label: 'DoorDash Plus — delivery commission (DashPass orders 27 %, pickup 8 %)', value: 25, unit: '%', source: 'merchants.doordash.com/en-ca/pricing', confidence: 'VERIFIED' },
  { id: 'plan_dd_premier', section: 'Published plans (info)', label: 'DoorDash Premier — delivery commission (pickup 8 %)', value: 29, unit: '%', source: 'merchants.doordash.com/en-ca/pricing', confidence: 'VERIFIED' },
  { id: 'plan_dd_tablet', section: 'Published plans (info)', label: 'DoorDash tablet (Canada) after trial, per week', value: 3, unit: '$', source: 'merchants.doordash.com/en-ca/pricing', confidence: 'VERIFIED' },
  { id: 'plan_skip', section: 'Published plans (info)', label: 'SkipTheDishes delivery commission (contract, not published; typical range 20–30 %)', value: 25, unit: '%', source: 'Secondary sources only', confidence: 'UNCERTAIN' },
];

export const EXPORTS_CHECKLIST: ExportItem[] = [
  { id: 'U1', platform: 'Uber Eats', report: 'Payment Details — one line per order, all stores (max 31 days per request → one file per month)', where: 'Uber Eats Manager → Reports → Request Reports → "Payment Details" → all stores → date range → download from Request History', range: 'First order → today, month by month', format: 'CSV', formats: ['uber_payment_details'], partial: ['uber_scan_payouts'] },
  { id: 'U2', platform: 'Uber Eats', report: 'Weekly Pay Summary + Payouts (status Paid / Pending / Rejected by Bank) + the "payouts on hold" message', where: 'Uber Eats Manager → Payments → Weekly Pay Summary → Download CSV; Payouts tab (screenshot what is on hold)', range: 'Since opening', format: 'CSV / screenshots', formats: ['uber_payouts'], partial: ['uber_scan_payouts'] },
  { id: 'U3', platform: 'Uber Eats', report: 'Uber → Restaurant invoices (GST/QST paid on Uber fees)', where: 'Invoice links in Payment Details (U2R), or Payments → invoices', range: 'Since opening', format: 'PDF', formats: [] },
  { id: 'U4', platform: 'Uber Eats', report: 'Order Errors (Transaction) — one row per error: customer refund, your charge, part Uber covered', where: 'Uber Eats Manager → Reports → Request Reports → "Order Errors (Transaction)"', range: 'Max 31 days per request', format: 'CSV', formats: [] },
  { id: 'D1', platform: 'DoorDash', report: 'Financial report — Transactions Breakdown (one line per order / transaction, all stores)', where: 'Merchant Portal → Reports → Create report → Financial → Transactions Breakdown → all stores (download within 7 days)', range: 'Last 2 years maximum (older: ask Support)', format: 'CSV', formats: ['doordash_transactions'], partial: ['doordash_scan_charges'] },
  { id: 'D2', platform: 'DoorDash', report: 'Payouts (payout ID, date, status, net payout, per store)', where: 'Merchant Portal → Reports → Create report → Financial → Payouts (Financials → Payouts to view)', range: 'Last 2 years', format: 'CSV', formats: ['doordash_payouts'] },
  { id: 'D3', platform: 'DoorDash', report: 'Monthly statements (by the 5th of each month) + fee invoices', where: 'Merchant Portal → Financials → Statements', range: 'Since opening', format: 'PDF', formats: [], partial: ['doordash_scan_charges'] },
  { id: 'D4', platform: 'DoorDash', report: 'Error charges (filter) and Cancelled orders (optional, for the cancellation cost)', where: 'Financials → Transactions → filter "Error charge"; Reports → Create report (Operations / Cancelled orders)', range: 'Last 2 years', format: 'CSV', formats: [], partial: ['doordash_scan_charges'] },
  { id: 'S1', platform: 'SkipTheDishes', report: 'Orders & earnings report (all locations) + weekly earnings statements', where: 'Skip restaurant portal → Reports → Generate Report → start/end date', range: 'Since opening', format: 'CSV (statements PDF)', formats: ['skip_statement'] },
  { id: 'C1', platform: 'Clover', report: 'Transactions / Payments export (tender, tip, tax, refunds)', where: 'clover.com → Sales activity (Transactions) → Payments → filter dates → Export', range: 'Since the merchant was created (May 2026) → today', format: 'CSV', formats: ['clover_payments'] },
  { id: 'C2', platform: 'Clover', report: 'Orders export (order type, total, tax, discounts, notes)', where: 'clover.com → Sales activity (Transactions) → Orders → Export', range: 'Same', format: 'CSV', formats: ['clover_orders'] },
  { id: 'C3', platform: 'Clover', report: 'Sales Overview — full report incl. taxes per tax rate (TPS, TVQ, "Sales Tax"), tenders, refunds', where: 'clover.com → Reporting → Sales Overview → Full Report → Export (over 3 months: Requested Reports)', range: 'Same, by month', format: 'CSV', formats: [] },
  { id: 'C4', platform: 'Clover', report: 'Deposits (Deposit Date, Amount Submitted, Chargebacks/Reversals, Fees/Adjustments, Amount Transferred) + monthly Merchant Processing Statement and Clover Plan & App Statement', where: 'clover.com → Reporting (Finances) → Deposits → Print (save as PDF; no CSV); Account & Setup → Monthly Statements', range: 'Past year (deposits page limit) + all statements', format: 'PDF (CSV if offered)', formats: ['clover_deposits'] },
  { id: 'B1', platform: 'Bank', report: 'Transaction history of every account receiving platform or Clover deposits (last 4 digits: see Stores / Money_Held)', where: 'Online banking → account → Transactions → Download CSV', range: 'Since the first payout', format: 'CSV', formats: ['bank'] },
  { id: 'O1', platform: 'Other', report: 'UrbanPiper invoices; tablet-fee invoices; GST/QST returns filed (periods, amounts)', where: 'Email / accountant', range: 'Since opening', format: 'PDF', formats: [] },
];
